#!/bin/bash

# Install ceph-deploy on ubuntu

# Disable check certificates
if [ ! -f ~/.wgetrc ]; then
    echo 'check_certificate=off' > ~/.wgetrc
fi

sudo apt-get install -y wget

# Add ceph-deploy repository
wget -q -O- 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc' | sudo apt-key add -
echo deb http://ceph.com/debian-dumpling/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
sudo apt-get update

sudo apt-get install -y ceph-deploy
